/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */
public class bt1 extends javax.swing.JFrame {

    /**
     * Creates new form bt1
     */
    public bt1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtA = new javax.swing.JTextField();
        txtB = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPhepToan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtKq = new javax.swing.JTextField();
        btnCộng = new javax.swing.JButton();
        btnChia = new javax.swing.JButton();
        btnTru = new javax.swing.JButton();
        btnNhân = new javax.swing.JButton();
        btnAns = new javax.swing.JButton();
        btnAc = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtb2 = new javax.swing.JTextField();
        txta1 = new javax.swing.JTextField();
        txta2 = new javax.swing.JTextField();
        txtb1 = new javax.swing.JTextField();
        txtc1 = new javax.swing.JTextField();
        txtkqx = new javax.swing.JTextField();
        txtc2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btngiai = new javax.swing.JButton();
        txtkqy = new javax.swing.JTextField();
        btnAc2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Máy Tính Cá Nhân");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 31, 290, 30));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 51, 0)));
        jPanel1.setForeground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)), "Các Phép Toán Cơ Bản", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("A=");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 28, 40, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("B=");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 50, 40));

        txtA.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtA.setToolTipText("nhập số ");
        jPanel2.add(txtA, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 130, 30));

        txtB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtB.setToolTipText("nhập số");
        txtB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBActionPerformed(evt);
            }
        });
        jPanel2.add(txtB, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 130, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Phép Toán");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 120, 50));

        txtPhepToan.setEditable(false);
        txtPhepToan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtPhepToan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPhepToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhepToanActionPerformed(evt);
            }
        });
        jPanel2.add(txtPhepToan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 150, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Kết Quả :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 110, 30));

        txtKq.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtKq.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtKq.setEnabled(false);
        jPanel2.add(txtKq, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 150, 40));

        btnCộng.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCộng.setText("+");
        btnCộng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCộngActionPerformed(evt);
            }
        });
        jPanel2.add(btnCộng, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, 40));

        btnChia.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnChia.setText("/");
        btnChia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiaActionPerformed(evt);
            }
        });
        jPanel2.add(btnChia, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 50, 40));

        btnTru.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnTru.setText("-");
        btnTru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTruActionPerformed(evt);
            }
        });
        jPanel2.add(btnTru, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 50, 40));

        btnNhân.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnNhân.setText("*");
        btnNhân.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhânActionPerformed(evt);
            }
        });
        jPanel2.add(btnNhân, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 50, 40));

        btnAns.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAns.setText("Ans");
        btnAns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnsActionPerformed(evt);
            }
        });
        jPanel2.add(btnAns, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));

        btnAc.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAc.setText("AC");
        btnAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcActionPerformed(evt);
            }
        });
        jPanel2.add(btnAc, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 70, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 550, 290));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2), "Giải hệ phương trình bậc một 2 ẩn", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel4.setToolTipText("Nhập hệ số b1");
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("x");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 50, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 70, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("y");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 40, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("=");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 50, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("+");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 40, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("x");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 50, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("+");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 60, 40));

        txtb2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtb2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtb2.setToolTipText("Nhập hệ số b2");
        txtb2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtb2CaretUpdate(evt);
            }
        });
        txtb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtb2ActionPerformed(evt);
            }
        });
        jPanel4.add(txtb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 80, 40));

        txta1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txta1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txta1.setToolTipText("Nhập hệ số a1");
        jPanel4.add(txta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 70, -1));

        txta2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txta2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txta2.setToolTipText("nhập hệ số a2");
        txta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txta2ActionPerformed(evt);
            }
        });
        jPanel4.add(txta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 70, -1));

        txtb1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtb1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtb1.setToolTipText("nhạp hệ số b1");
        jPanel4.add(txtb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 80, -1));

        txtc1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtc1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtc1.setToolTipText("nhập hệ số c1");
        jPanel4.add(txtc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 80, 40));

        txtkqx.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtkqx.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtkqx.setEnabled(false);
        txtkqx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkqxActionPerformed(evt);
            }
        });
        jPanel4.add(txtkqx, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 120, 50));

        txtc2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtc2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtc2.setToolTipText("Nhậphệ số c2");
        jPanel4.add(txtc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 80, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("y");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 20, 60));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("=");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 60, 50));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Kết Quả :");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 110, 50));

        btngiai.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btngiai.setText("Giải");
        btngiai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngiaiActionPerformed(evt);
            }
        });
        jPanel4.add(btngiai, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 100, 60));

        txtkqy.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtkqy.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtkqy.setEnabled(false);
        jPanel4.add(txtkqy, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 130, 50));

        btnAc2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAc2.setText("AC");
        btnAc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAc2ActionPerformed(evt);
            }
        });
        jPanel4.add(btnAc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 130, 50));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 550, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBActionPerformed

    private void txtPhepToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhepToanActionPerformed
       
    }//GEN-LAST:event_txtPhepToanActionPerformed

    private void btnCộngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCộngActionPerformed
        double a = Double.parseDouble(txtA.getText());
        double b = Double.parseDouble(txtB.getText());
        double Tong = a+b;
        txtPhepToan.setText("+");
        txtKq.setText(String.valueOf (Tong));
    }//GEN-LAST:event_btnCộngActionPerformed

    private void btnTruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTruActionPerformed
        double a = Double.parseDouble(txtA.getText());
        double b = Double.parseDouble(txtB.getText());
        double Tru = a-b;
        txtPhepToan.setText("-");
        txtKq.setText(String.valueOf (Tru));
    }//GEN-LAST:event_btnTruActionPerformed

    private void btnNhânActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhânActionPerformed
        double a = Double.parseDouble(txtA.getText());
        double b = Double.parseDouble(txtB.getText());
        double Nhan = a*b;
        txtPhepToan.setText("*");
        txtKq.setText(String.valueOf (Nhan));
    }//GEN-LAST:event_btnNhânActionPerformed

    private void btnChiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiaActionPerformed
        double a = Double.parseDouble(txtA.getText());
        double b = Double.parseDouble(txtB.getText());
        double Chia = a/b;
        txtPhepToan.setText("/");
        txtKq.setText(String.valueOf (Chia));
    }//GEN-LAST:event_btnChiaActionPerformed

    private void btnAcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcActionPerformed
       txtA.setText("");
       txtB.setText("");
       txtKq.setText("");
    }//GEN-LAST:event_btnAcActionPerformed

    private void btnAnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnsActionPerformed
       txtA.setText(txtKq.getText());
    }//GEN-LAST:event_btnAnsActionPerformed

    private void txtb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtb2ActionPerformed

    private void txta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txta2ActionPerformed

    private void txtb2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtb2CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtb2CaretUpdate

    private void btngiaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngiaiActionPerformed
       double a1 = Double.parseDouble(txta1.getText());
       double b1 = Double.parseDouble(txtb1.getText());
       double c1 = Double.parseDouble(txtc1.getText());
       double a2 = Double.parseDouble(txta2.getText());
       double b2 = Double.parseDouble(txtb2.getText());
       double c2 = Double.parseDouble(txtc2.getText());
       double d = (a2*b1) - (a1*b2);
       double dx = (c2*b1) - (c1*b2);
       double dy = (a2*c1) - (a1*c2);
       if(d !=0)
       {
           if((dx != dy) && (dx != 0) && (dy != 0))
           {
               double x = dx/d;
               double y = dy/d;
               txtkqx.setText(String.valueOf(x));
               txtkqy.setText(String.valueOf(y));
           }
           else if((dx == dy))
           {
                if((dx !=0) && (dy !=0))
                {
                    double x = dx/d;
                    double y = dy/d;
                    txtkqx.setText(String.valueOf(x));
                    txtkqy.setText(String.valueOf(y));
                }
            
                else txtkqx.setText(" hệ phương trình có vô số nghiệm");     
           }
       }
        else txtkqx.setText("hệ phương trình vô nghiệm");
    }//GEN-LAST:event_btngiaiActionPerformed

    private void txtkqxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkqxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkqxActionPerformed

    private void btnAc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAc2ActionPerformed
       txta1.setText("");
       txtb1.setText("");
       txtc1.setText("");
       txta2.setText("");
       txtb2.setText("");
       txtc2.setText("");
       txtkqy.setText("");
       txtkqx.setText("");
       
    }//GEN-LAST:event_btnAc2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bt1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bt1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bt1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bt1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bt1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAc;
    private javax.swing.JButton btnAc2;
    private javax.swing.JButton btnAns;
    private javax.swing.JButton btnChia;
    private javax.swing.JButton btnCộng;
    private javax.swing.JButton btnNhân;
    private javax.swing.JButton btnTru;
    private javax.swing.JButton btngiai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtKq;
    private javax.swing.JTextField txtPhepToan;
    private javax.swing.JTextField txta1;
    private javax.swing.JTextField txta2;
    private javax.swing.JTextField txtb1;
    private javax.swing.JTextField txtb2;
    private javax.swing.JTextField txtc1;
    private javax.swing.JTextField txtc2;
    private javax.swing.JTextField txtkqx;
    private javax.swing.JTextField txtkqy;
    // End of variables declaration//GEN-END:variables
}
