/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thuc.hanh.pkg2;

import java.awt.Label;
import javax.swing.JOptionPane;

/**
 *
 * @author asus
 */
public class login extends javax.swing.JFrame {

                Label lblthongbao;
                
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txttendn = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        btndangnhap = new javax.swing.JButton();
        btnans = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Tên Đăng Nhập");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 34, 170, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Mật Khẩu");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 140, 40));

        txttendn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txttendn.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txttendn.setText("57130781");
        txttendn.setToolTipText("Nhập MSSV");
        txttendn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttendnActionPerformed(evt);
            }
        });
        getContentPane().add(txttendn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 350, -1));

        pass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pass.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pass.setText("1997");
        pass.setToolTipText("nhập NS");
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 270, 30));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btndangnhap.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btndangnhap.setText("Đăng Nhập");
        btndangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndangnhapActionPerformed(evt);
            }
        });
        jPanel1.add(btndangnhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 180, 50));

        btnans.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnans.setText("CLEAR");
        btnans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnansActionPerformed(evt);
            }
        });
        jPanel1.add(btnans, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 100, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttendnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttendnActionPerformed
       
    }//GEN-LAST:event_txttendnActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void btndangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndangnhapActionPerformed
              String Ten = txttendn.getText();
              String pw = pass.getText();
              if ( Ten.equals("57130781") && pw.equals( "1997") )
                      
              {
                        new login3().setVisible(true);
                        setVisible(false);
              }
              else JOptionPane.showMessageDialog(null,"khong thanh cong");
    }//GEN-LAST:event_btndangnhapActionPerformed

    private void btnansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnansActionPerformed
                  txttendn.setText("");
                  pass.setText("");
    }//GEN-LAST:event_btnansActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnans;
    private javax.swing.JButton btndangnhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField txttendn;
    // End of variables declaration//GEN-END:variables
}
