/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thuc.hanh.pkg2;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author asus
 */
public class login3 extends javax.swing.JFrame {

    String gt = "Nam";
    arrylistclass ards;
    int kt = 0, i = 0, stt = 1, t = 0;
    ArrayList<String> dssv = new ArrayList<String>();
    public login3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtten = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtns = new javax.swing.JTextField();
        rdbnam = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        rdnnu = new javax.swing.JRadioButton();
        btnthem = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        ntnnapvao = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAbangten = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Nam");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Họ Tên");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 80, 40));

        txtten.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtten.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtten.setToolTipText("Nhập Tên");
        txtten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttenActionPerformed(evt);
            }
        });
        getContentPane().add(txtten, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 320, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Năm Sinh");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 110, 30));

        txtns.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtns.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtns.setToolTipText("Nhập NS");
        getContentPane().add(txtns, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 160, -1));

        buttonGroup1.add(rdbnam);
        rdbnam.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rdbnam.setSelected(true);
        rdbnam.setText("Nam");
        rdbnam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbnamActionPerformed(evt);
            }
        });
        getContentPane().add(rdbnam, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Giới Tính");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 100, 30));

        buttonGroup1.add(rdnnu);
        rdnnu.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rdnnu.setText("Nữ");
        rdnnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdnnuActionPerformed(evt);
            }
        });
        getContentPane().add(rdnnu, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, -1));

        btnthem.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });
        getContentPane().add(btnthem, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 100, -1));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 340));

        ntnnapvao.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ntnnapvao.setText("Nạp Vào");
        ntnnapvao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ntnnapvaoActionPerformed(evt);
            }
        });
        getContentPane().add(ntnnapvao, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 130, 50));

        txtAbangten.setColumns(20);
        txtAbangten.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        txtAbangten.setRows(5);
        txtAbangten.setText("STT----HỌ TÊN-----NĂM SINH----GIỚI TÍNH");
        jScrollPane1.setViewportView(txtAbangten);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 550, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttenActionPerformed

    private void rdbnamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbnamActionPerformed
        gt="Nam";
    }//GEN-LAST:event_rdbnamActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
             t = 1;
        if((txtten.getText().equals("") || txtten.getText().equals(null)) 
                || (txtns.getText().equals("") || txtns.getText().equals(null))) 
            JOptionPane.showConfirmDialog(this, "dữ liệu nhập vào trống","thông báo lỗi",JOptionPane.WARNING_MESSAGE);
        else
        {
            i = dssv.size();
            ards = new arrylistclass(txtten.getText(), txtns.getText(), gt);
            if(dssv.contains(ards.getht() + ards.getns() + ards.getgt()) == true)
            {
                JOptionPane.showMessageDialog(this, "dữ ,iệu nhập vào đã bị trùng","thông báo sự cố",JOptionPane.WARNING_MESSAGE);
                kt = 1;
            }
            else kt = 0;
            if(kt == 0) dssv.add(ards.getht() + ards.getns() + ards.getgt());
        }
    }//GEN-LAST:event_btnthemActionPerformed

    private void ntnnapvaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ntnnapvaoActionPerformed
       if(dssv.size() !=0 && stt <= dssv.size() && t == 1 ) 
        {
           txtAbangten.append("\n" + ards.xuat(String.valueOf(stt)));
           stt++;
           t = 0;
        }
        else if(dssv.size() == 0 ) 
            JOptionPane.showMessageDialog(this, "không có dữ liệu nạp vào","thông báo lỗi",JOptionPane.WARNING_MESSAGE);
        else if(stt > dssv.size() || t == 0) 
            JOptionPane.showMessageDialog(this, "dữ liệu không thể nạp vào","thông báo lỗi",JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_ntnnapvaoActionPerformed

    private void rdnnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdnnuActionPerformed
       gt="Nữ";
    }//GEN-LAST:event_rdnnuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnthem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton ntnnapvao;
    private javax.swing.JRadioButton rdbnam;
    private javax.swing.JRadioButton rdnnu;
    private javax.swing.JTextArea txtAbangten;
    private javax.swing.JTextField txtns;
    private javax.swing.JTextField txtten;
    // End of variables declaration//GEN-END:variables
}
