/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thuc.hanh.pkg3;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author asus
 */
public class danhsach extends javax.swing.JFrame {

    int stt, stt2;
    ArrayList<String> arrthethao = new ArrayList<>();
    ArrayList<String> arrmonyeuthich = new ArrayList<>();
     String tenchon, tenchon2;
    public danhsach() {
        initComponents();
         ListModel model = lstthethao.getModel();
            for(int i=0; i<=lstthethao.getLastVisibleIndex(); i++)
            {
                String ten= model.getElementAt(i).toString();
                arrthethao.add(ten); 
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstthethao = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstmonyeuthich = new javax.swing.JList();
        btnsangphai = new javax.swing.JButton();
        btntatcasangphai = new javax.swing.JButton();
        btnsangtrai = new javax.swing.JButton();
        btntatcasangtrai = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnthem = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("List veiw bài 3");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Ds Môn Thể Thao");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Môn Yêu Thích");

        lstthethao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lstthethao.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Bóng Đá", "Cầui Lông", "Bơi Lội", "Tennis", "Điền kinh", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstthethao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstthethaoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstthethao);

        lstmonyeuthich.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lstmonyeuthich.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstmonyeuthichMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lstmonyeuthich);

        btnsangphai.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnsangphai.setText(">");
        btnsangphai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsangphaiActionPerformed(evt);
            }
        });

        btntatcasangphai.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btntatcasangphai.setText(">>");
        btntatcasangphai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntatcasangphaiActionPerformed(evt);
            }
        });

        btnsangtrai.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnsangtrai.setText("<");
        btnsangtrai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsangtraiActionPerformed(evt);
            }
        });

        btntatcasangtrai.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btntatcasangtrai.setText("<<");
        btntatcasangtrai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntatcasangtraiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 59, Short.MAX_VALUE)
        );

        btnthem.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnthem.setText("+");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnsangphai, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(97, 97, 97))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btnsangtrai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btntatcasangtrai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnthem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(btntatcasangphai))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(91, 91, 91))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(btnsangphai)
                            .addGap(22, 22, 22)
                            .addComponent(btntatcasangphai)
                            .addGap(18, 18, 18)
                            .addComponent(btnsangtrai)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btntatcasangtrai)
                            .addGap(26, 26, 26)
                            .addComponent(btnthem)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsangphaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsangphaiActionPerformed
                     ListModel model = lstthethao.getModel();
                    arrmonyeuthich.add(model.getElementAt(stt).toString());
                    arrthethao.remove(model.getElementAt(stt).toString());
                    Object[] mTen = arrmonyeuthich.toArray();
                    Object [] mthao=arrthethao.toArray();
                    lstmonyeuthich.setListData(mTen);
                    lstthethao.setListData(mthao);
    }//GEN-LAST:event_btnsangphaiActionPerformed

    private void lstthethaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstthethaoMouseClicked
        stt = lstthethao.getSelectedIndex();
    }//GEN-LAST:event_lstthethaoMouseClicked

    private void btntatcasangphaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntatcasangphaiActionPerformed
            ListModel model = lstthethao.getModel();
            for(int i=0; i<=lstthethao.getLastVisibleIndex(); i++)
            {
                arrmonyeuthich.add(model.getElementAt(i).toString());
                arrthethao.remove(model.getElementAt(i).toString());   
            }
            Object [] mten= arrmonyeuthich.toArray();
            Object [] mthich= arrthethao.toArray();
            lstmonyeuthich.setListData(mten);
            lstthethao.setListData(mthich);
    }//GEN-LAST:event_btntatcasangphaiActionPerformed

    private void btnsangtraiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsangtraiActionPerformed
                    ListModel model = lstmonyeuthich.getModel();
                    arrthethao.add( model.getElementAt(stt2).toString());
                    arrmonyeuthich.remove( model.getElementAt(stt2).toString());
                    Object[] mTen = arrthethao.toArray();
                    Object [] mthao=arrmonyeuthich.toArray();
                    lstthethao.setListData(mTen);
                    lstmonyeuthich.setListData(mthao);
    }//GEN-LAST:event_btnsangtraiActionPerformed

    private void lstmonyeuthichMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstmonyeuthichMouseClicked
         stt2 = lstmonyeuthich.getSelectedIndex();
    }//GEN-LAST:event_lstmonyeuthichMouseClicked

    private void btntatcasangtraiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntatcasangtraiActionPerformed
        ListModel model = lstmonyeuthich.getModel();
            for(int i=0; i<=lstmonyeuthich.getLastVisibleIndex(); i++)
            {
                arrthethao.add(model.getElementAt(i).toString());
                arrmonyeuthich.remove(model.getElementAt(i).toString());   
            }
            Object [] mten= arrmonyeuthich.toArray();
            Object [] mthao = arrthethao.toArray();
            lstmonyeuthich.setListData(mten);
            lstthethao.setListData(mthao);
    }//GEN-LAST:event_btntatcasangtraiActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
            String them = JOptionPane.showInputDialog(this,"nhập thêm môn thể thao","thông báo",JOptionPane.INFORMATION_MESSAGE);
            if(them != "") 
            {
                if(!arrthethao.contains(them))
                {
                    arrthethao.add(them);
                    Object [] mthich= arrthethao.toArray();
                    lstthethao.setListData(mthich);
                }
                else
                    JOptionPane.showMessageDialog(this, "không thể thêm dữ liệu đã tồn tại","thông báo",JOptionPane.WARNING_MESSAGE);
            }
            else
                JOptionPane.showMessageDialog(this, "không thể thêm dữ liệu rổng","thông báo",JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnthemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(danhsach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(danhsach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(danhsach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(danhsach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new danhsach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsangphai;
    private javax.swing.JButton btnsangtrai;
    private javax.swing.JButton btntatcasangphai;
    private javax.swing.JButton btntatcasangtrai;
    private javax.swing.JButton btnthem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList lstmonyeuthich;
    private javax.swing.JList lstthethao;
    // End of variables declaration//GEN-END:variables
}
